Name:           ros-hydro-jaco-ros
Version:        1.0.1
Release:        2%{?dist}
Summary:        ROS jaco_ros package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/jaco_ros
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-jaco-demo
Requires:       ros-hydro-jaco-driver
Requires:       ros-hydro-jaco-model
Requires:       ros-hydro-jaco-msgs
BuildRequires:  ros-hydro-catkin

%description
The ROS JACO Arm metapackage provides a ROS interface for the Kinova Robotics
JACO robotic manipulator arm. This metapackage provides access to the Kinova
JACO C++ hardware API through ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Aug 11 2014 Ilia Baranov (Clearpath) <ibaranov@clearpathrobotics.com> - 1.0.1-2
- Autogenerated by Bloom

* Sun Aug 10 2014 Ilia Baranov (Clearpath) <ibaranov@clearpathrobotics.com> - 1.0.0-0
- Autogenerated by Bloom

* Mon Aug 11 2014 Ilia Baranov (Clearpath) <ibaranov@clearpathrobotics.com> - 1.0.1-0
- Autogenerated by Bloom

* Mon Aug 11 2014 Ilia Baranov (Clearpath) <ibaranov@clearpathrobotics.com> - 1.0.1-1
- Autogenerated by Bloom

